### ISSUE TITLE
反馈亿点点问题，如果作者感到不适可以当我放屁

### ISSUE THREAD

**Issue by winds365** [Xinrea/JLiverTool#19]
1.设置鼠标穿透或置顶之后，不应该会被最小化
2.弹幕颜色设置，弹幕消失时间设置
3.鼠标穿透情况下，顶部标题栏背景透明，底部状态栏隐藏
4.透明度好像也对弹幕生效？
5.字体大小好像最小只能到14，建议放开限制；标题栏、状态栏字体大小跟弹幕字体大小单独设置
6.弹幕窗口宽度解除最小宽度限制

**Comment by Xinrea** [comment]
标题栏和状态栏字体大小的设置不直接提供，后续待新增的自定义样式功能能够实现这一点；其余提到的问题均在 2.0.0 的重构版本进行了解决。
