### ISSUE TITLE
几个建议

### ISSUE THREAD

**Issue by zxp19821005** [Xinrea/JLiverTool#20]
我已经将该软件移植到了ArchLinux的AUR：[jlivertool](https://aur.archlinux.org/packages/jlivertool)，目前运行正常。
运行过程中，有几个问题：
- 能否在package.json中加入Linux编译脚本？如`"build-linux": "npx webpack && cross-env NODE_ENV=production electron-builder build -l --publish=never"`
- 编译完成运行后，程序系统栏图标显示正常，任务栏无图标显示，不知道这个能否修复一下？不知道任务栏调用的图标文件是`ico文件`还是`png文件`？或者能否改为`png文件`

**Comment by Xinrea** [comment]
添加上了 linux 版本的构建，1.4.1 版本手动补充了一些 Release；后续版本会自动构建上传 linux 版本。
关于图标的问题已经修复，主要是这个原因导致的：
https://github.com/electron-userland/electron-builder/issues/5294
可以尝试使用 pacman 包安装，目前应该都正常了。

AppImage 的图标的话，需要 https://github.com/TheAssassin/AppImageLauncher 等工具的支持。
