### ISSUE TITLE
在直播过程中会串流在其他的直播间去

### ISSUE THREAD

**Issue by rettt767** [Xinrea/JLiverTool#30]
主诉：直播间进行连接的时候，党委i将直播间设置到我这边的时候会出现幽灵弹幕，而且同接数量也有问题：
![image](https://github.com/Xinrea/JLiverTool/assets/71586035/09766df7-f7c0-4048-a533-76cfa272d651)
在正常情况下，同接数应该是1, 且我在自己进行弹幕验证的时候，发现弹幕并没有出现，我怀疑这个弹幕是其他直播间的。

是否是因为当前的包内部存在测试时的数据？如若有，请做一下代码检查，因为不会保证安全性。

**Comment by rettt767** [comment]
更新他的状态，其会出现幽灵弹幕和错误的同接数，但是这是暂时的

**Comment by Xinrea** [comment]
包内目前不存在自带的直播间号等信息，考虑到未从其他主播收到此反馈，因此猜测可能是因为新直播间号目前过大，超过了 js 的 parseInt 处理范围导致房间号不一致，会考虑对涉及到的相关部分进行改动处理；
如果能够提供一下出现问题直播间号的大致数据范围就更好了，可以印证一下。

**Comment by Retcl** [comment]
多谢回复，当前我的直播间号为：9490773，在我进行相关的直播时，就会出现不存在的弹幕和获取同接的问题。
另：接下来请回复到raft_float@outlook.com这个邮箱中，此邮箱在近期可能会被弃用。
现在我暂时无法使用电脑对代码进行分析，再过两天我回重庆后我回对代码进行细致的分析，谢谢

**Comment by Retcl** [comment]
> 包内目前不存在自带的直播间号等信息，考虑到未从其他主播收到此反馈，因此猜测可能是因为新直播间号目前过大，超过了 js 的 parseInt 处理范围导致房间号不一致，会考虑对涉及到的相关部分进行改动处理；
> 如果能够提供一下出现问题直播间号的大致数据范围就更好了，可以印证一下。

多谢回复，当前我的直播间号为：9490773，在我进行相关的直播时，就会出现不存在的弹幕和获取同接的问题。
另：接下来请回复到raft_float@outlook.com这个邮箱中，此邮箱在近期可能会被弃用。
现在我暂时无法使用电脑对代码进行分析，再过两天我回重庆后我回对代码进行细致的分析，谢谢
