### ISSUE TITLE
给老板打call，我准备在这个基础上加发送弹幕的功能，需要手动输入cookie或者接上登录

### ISSUE THREAD

**Issue by yaocccc** [Xinrea/JLiverTool#5]
另外如果 弹幕主窗口、礼物、停留消息能在一个window里就更好了。可以pin在一个窗口上不需要目前这样开3个

**Comment by Xinrea** [comment]
现在礼物和SC窗口不单独打开的话，都是显示在主窗口的；子窗口打开后才会分开显示。如果加上登录的话，其实改直播间标题和下播这种操作其实也可以加上，也挺常见的
