### ISSUE TITLE
最小化到任务栏

### ISSUE THREAD

**Issue by ixinshang** [Xinrea/JLiverTool#7]
工具很好用。
windows，要是能最小话到任务栏就好了。
不知有计划支持不

**Comment by ixinshang** [comment]
@Xinrea 你好，桌面展示的时候，能否增加一个透明度和鼠标穿过的功能。

**Comment by Xinrea** [comment]
> @Xinrea 你好，桌面展示的时候，能否增加一个透明度和鼠标穿过的功能。

没问题，会在下次更新时一并加入

**Comment by ixinshang** [comment]
> > @Xinrea 你好，桌面展示的时候，能否增加一个透明度和鼠标穿过的功能。
> 
> 没问题，会在下次更新时一并加入

期待新版本。
